### ISSUE TITLE
Django app anlegen

### ISSUE THREAD

**Issue by josieFoo** [josieFoo/FantasieBoard#3]
-  python manage.py startapp fantasieboard.
-  django tutorial wiederholen.
-  model erstellen.

**Comment by josieFoo** [comment]
- App initiiert.
- (Tutorial bzw. Reference) https://youtu.be/F5mRW0jo-U4

**Comment by josieFoo** [comment]
- Was soll damit gemacht werden:
   - db.sqlite3, urls.cpython-38.pyc, wsgi.cpython-38.pyc

**Comment by Mantelmann** [comment]
In die .gitignore schreiben, am Besten eine Wildcard für alle *.pyc Dateien. Es gibt schöne Presets für gitignore-Dateien für Django-Projekte.

Am 8. Dezember 2021 11:47:26 MEZ schrieb josieFoo ***@***.***>:

**Comment by josieFoo** [comment]
- Problem 1
     - Brauche man das Attribut 'id'? primary keys werden von Django intern automatisch erzeugt. Vielleicht braucht man nur foreign keys einzustellen?
```python
class Community(models.Model):
	id = models.AutoField(primary_key=True)
	community_name = models.CharField(blank=False, max_length=32)
```
 
- Problem 2
     - 'pseudo_name' sollte auch primary key sein, aber dann error. Es erlaubt nur ein primary key.
```python
class Users(models.Model):
	user_id = models.AutoField(primary_key=True)
	superuser = models.BooleanField(null=False, default=False)
	pseudo_name = models.CharField(blank=False, max_length=16)
	created_at = models.DateField(auto_now_add=True)
	mail_address = models.EmailField(max_length=254, blank=False)
	password = models.CharField(blank=False, max_length=16)
```

- Problem 3
    - Es läuft nicht korrekt.
```python
class Community_moderator(models.Model):
	community_id = models.ForeignKey(Community, on_delete=models.CASCADE)
	admin_id = models.ForeignKey(Users, on_delete=models.CASCADE)
```
  
# Issue #3 Versehentlich geschlossen.

**Comment by Mantelmann** [comment]
1: Nein. Wenn kein Primary Key explizit angegeben ist, dann wird ein Default- PK mit Namen "pk" (glaube ich) im Hintergrund generiert.

2: Benutze das Attribut unique=True. Dann kann es noch immer nur ein Objekt mit dem Schlüssel geben, und es wird noch zusätzlich ein PK generiert.

3. Im Unisportomaten habe ich ForeignKey("Name", ...) geschrieben, als String ging das.

Am 8. Dezember 2021 20:32:40 MEZ schrieb josieFoo ***@***.***>:

**Comment by josieFoo** [comment]
- Models sind im Django-Admin-Ansicht zu sehen.
- Wird voraussichtlich geschlossen.
