### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by josieFoo** [josieFoo/FantasieBoard#5]
- Was brauche ich?

**Comment by josieFoo** [comment]
- Views
-   - Was brauche ich?

**Comment by josieFoo** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/65567887/147134330-eba6a5c0-bb9d-4fde-bcc8-62ceada6eb61.png">

**Comment by josieFoo** [comment]
- Überlegen was meine Views tun sollen:

**Comment by josieFoo** [comment]
> * Überlegen was meine Views tun sollen:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/65567887/147264170-f6d5cf59-0ef9-484d-a219-139ed995a1ab.png">

**Comment by josieFoo** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/65567887/147302999-99a2d394-a11d-4a09-894e-acaf22b10a9b.png">
<img width="218" alt="image" src="https://user-images.githubusercontent.com/65567887/147303015-5ea6a080-0d26-405c-bbcc-1fb12e2abc82.png">

**Comment by josieFoo** [comment]
- Wie greife ich zu meiner DB?
<img width="263" alt="image" src="https://user-images.githubusercontent.com/65567887/147303269-8c41884d-de5a-4127-b4d9-402f69ee91f4.png">

- Aber ich brauche alle Namen von communities und als 'Anker'. Wie?

**Comment by josieFoo** [comment]
> * Wie greife ich zu meiner DB?
> 
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/65567887/147303269-8c41884d-de5a-4127-b4d9-402f69ee91f4.png">
> 
> * Aber ich brauche alle Namen von communities und als 'Anker'. Wie?
 Done.
```python
def community_view(request, *args, **kwargs):
	"""
	Shows a list of communities which can be joined by users.
	'community.html' extends 'index.html'.
	"""
	queryset = Community.objects.all()
	context = {
		"community_list": queryset,
	}
	return render(request, "community.html", context)
```

**Comment by josieFoo** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/65567887/147307959-f5ee2010-77ac-402a-a788-7ef4e3b46920.png">

**Comment by josieFoo** [comment]
- TODO:
  - Die Links sind nicht richtig.
  - Wenn z.B. 'Starcraft' geclickt, soll bspw. starcraft.html dynamisch erzeugt werden.
  - Und die Seite enthält die 'Articles', die auch von der DB gelesen wurden.

**Comment by josieFoo** [comment]
> * TODO:
>   
>   * Die Links sind nicht richtig.
>   * Wenn z.B. 'Starcraft' geclickt, soll bspw. starcraft.html dynamisch erzeugt werden.
>   * Und die Seite enthält die 'Articles', die auch von der DB gelesen wurden.

Done

**Comment by josieFoo** [comment]
- View für 'Articles' mit der selben Vorgehensweise.
  z.B: '27.0.0.1:8000/articles/{id}'

**Comment by josieFoo** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/65567887/147373523-b0a8775a-3b3d-4762-8ad1-f543457894c3.png">

**Comment by josieFoo** [comment]
- Problem
   - 'http://127.0.0.1:8000/community/DnD/1' ist korrekt: aber Internal Server Error
> * Resolved

**Comment by josieFoo** [comment]
- Problem

<img width="487" alt="image" src="https://user-images.githubusercontent.com/65567887/147667035-e3edd1ff-04a0-42ec-aec1-c54e8daa8246.png">

**Comment by Mantelmann** [comment]
In Django sind die letzten Slashes am Ende der URL wichtig. Deine URLs haben kein Slash am Ende, erwarten also

```
community/DnD/1
```

anstelle von

```
community/DnD/1/
```

Und ich sehe gerade, dass du für Kommentare auch nochmal jeweils eine URL haben möchtest. Frage: Warum willst du die haben?

**Comment by josieFoo** [comment]
> In Django sind die letzten Slashes am Ende der URL wichtig. Deine URLs haben kein Slash am Ende, erwarten also
> 
> ```
> community/DnD/1
> ```
> 
> anstelle von
> 
> ```
> community/DnD/1/
> ```
> 
> Und ich sehe gerade, dass du für Kommentare auch nochmal jeweils eine URL haben möchtest. Frage: Warum willst du die haben?

Ja, habe vor ein paar Minuten gemerkt, dass das ein Blödsinn ist, für jedes Kommentar ein URL zu geben. Und habe umgeschrieben, sodass die Kommentare mit dem Article zusammen gerendert werden.

**Comment by josieFoo** [comment]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/65567887/147670228-5285b94f-a41f-44a2-960f-0dc7802f5477.png">

**Comment by josieFoo** [comment]
- Der Filter hatte falsches Argument. Korrigiert.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/65567887/147672000-bac94d6f-99d5-4ae1-8c27-cbb800dcd5a1.png">

**Comment by josieFoo** [comment]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/65567887/147693346-839f23d6-2035-403c-8f05-4c157aa99b96.png">

<img width="274" alt="image" src="https://user-images.githubusercontent.com/65567887/147693365-b0d210c7-691d-4226-8190-fbe70aa84f18.png">

<img width="275" alt="image" src="https://user-images.githubusercontent.com/65567887/147693394-f4d9b08c-80f1-481d-82ce-03a4c906e8c3.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/65567887/147693286-09b86590-3be8-4e32-8107-ca9b9cc4afed.png">
