### ISSUE TITLE
Profile page for User

### ISSUE THREAD

**Issue by josieFoo** [josieFoo/FantasieBoard#6]

**Comment by josieFoo** [comment]
- Was kann 'Profile View' enthalten?
  - Pseudoname.
  - Angegebene E-Mail Adresse
  - Wann wurde erstellt?
  - Wieviel Beiträge/Kommentare geschrieben?
  - Vielleicht Profilebilder.

**Comment by Mantelmann** [comment]
Challenge: Alle Beiträge und Kommentare in reverse-chronologischer Reihenfolge.

**Comment by josieFoo** [comment]
> Challenge: Alle Beiträge und Kommentare in reverse-chronologischer Reihenfolge.

Ich brauche mehr Tipps. ;)

**Comment by josieFoo** [comment]
- Nach dem Issue #7 kann geschlossen werden.
